let column1= document.querySelector(".column1")

let q1c1= document.querySelector("#q1c1")
let q2c1= document.querySelector("#q2c1")
let q3c1= document.querySelector("#q3c1")
let q4c1= document.querySelector("#q4c1")
let q5c1= document.querySelector("#q5c1")
let q1c2= document.querySelector("#q1c2")
let q2c2= document.querySelector("#q2c2")
let q3c2= document.querySelector("#q3c2")
let q4c2= document.querySelector("#q4c2")
let q5c2= document.querySelector("#q5c2")
let q1c3= document.querySelector("#q1c3")
let q2c3= document.querySelector("#q2c3")
let q3c3= document.querySelector("#q3c3")
let q4c3= document.querySelector("#q4c3")
let q5c3= document.querySelector("#q5c3")
let q1c4= document.querySelector("#q1c4")
let q2c4= document.querySelector("#q2c4")
let q3c4= document.querySelector("#q3c4")
let q4c4= document.querySelector("#q4c4")
let q5c4= document.querySelector("#q5c4")
let q1c5= document.querySelector("#q1c5")
let q2c5= document.querySelector("#q2c5")
let q3c5= document.querySelector("#q3c5")
let q4c5= document.querySelector("#q4c5")
let q5c5= document.querySelector("#q5c5")

q1c1.addEventListener("click", e => {
    e.preventDefault()
    console.log("button hit")
})